Fix up ticket name

diff --git a/.github/workflows/migrate.yaml b/.github/workflows/migrate.yaml
--- a/.github/workflows/migrate.yaml
+++ b/.github/workflows/migrate.yaml
@@ -62,11 +62,12 @@ jobs:
       - name: Set ticket name
         run: |
           TICKET_NAME=$(echo ${{ env.BRANCH_NAME }} | sed -E 's/tickets\/(DM-[0-9]+).*/\1/')
-          echo "TICKET_NAME=${TICKET_NAME}" >> $GITHUB_ENV
-          if [[ ! "${{ env.TICKET_NAME }}" =~ ^DM-[0-9]+$ ]]; then
-            echo "Error: TICKET_NAME does not match the expected pattern 'DM-[number]'." >&2
+          if [[ ! "${TICKET_NAME}" =~ ^DM-[0-9]+$ ]]; then
+            echo "Failed to get valid ticket name from: ${{ env.BRANCH_NAME }}" >&2
             exit 1
           fi
+          echo "TICKET_NAME=${TICKET_NAME}" >> $GITHUB_ENV
+          echo "Ticket name: $TICKET_NAME"
 
       - name: Checkout sdm_schemas repo
         uses: actions/checkout@v4
